# Generated by Django 4.2.7 on 2023-12-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('id_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.club')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('id_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.device')),
                ('id_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.service')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time1', models.DateTimeField()),
                ('time2', models.DateTimeField()),
                ('id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.client')),
                ('id_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.price')),
            ],
        ),
    ]
