# Generated by Django 4.2.7 on 2023-12-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time1',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time2',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
