# Generated by Django 4.2.7 on 2023-12-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compClub', '0002_alter_order_time1_alter_order_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time2',
        ),
    ]
