# Generated by Django 4.2.7 on 2023-12-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compClub', '0003_remove_order_time1_remove_order_time2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Каталог клиентов'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name', 'address'], 'verbose_name': 'Клубы', 'verbose_name_plural': 'Каталог клубов'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['name', 'description'], 'verbose_name': 'Устройства', 'verbose_name_plural': 'Каталог устройств'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'Заказы', 'verbose_name_plural': 'Журнал заказов'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price'], 'verbose_name': 'Цены', 'verbose_name_plural': 'Прейскурант цен'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуги', 'verbose_name_plural': 'Каталог услуг'},
        ),
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(max_length=255, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.TextField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='club',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.price', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compClub.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Название'),
        ),
    ]
